#!/usr/bin/perl
use Mojolicious::Lite;

use lib 'lib';

plugin 'PQGridCrud';
plugin 'RESTRoutes';
my $r = app->routes;
for ('a'..'d') {
  my $emr = $r->under("/emr_$_");
  $emr->route('/patients')->to("Emr\u${_}::Patients")->get->to("#index");
  $emr->rest_routes(name => 'patients', controller => "Emr\u${_}::Patients");
  $emr->route('/vitals')->to("Emr\u${_}::Vitals")->get->to("#index");
  $emr->rest_routes(name => 'vitals', controller => "Emr\u${_}::Vitals");
}

get '/' => sub {
  my $self = shift;
  $self->render('index');
};


app->start;

__DATA__
@@ index.html.ep
hi
